name: Deploy web
on:
  workflow_dispatch:
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }
      - run: npm install
      - run: npm run build
      - run: npx wix release
        env:
          WIX_API_KEY: ${{ secrets.WIX_API_KEY }}
